-- SQL Script to Set Up AVS Backend Database

-- Create Table for OTP Records
CREATE TABLE [tbl_MobileOTPLogin] (
    [Id] INT IDENTITY(1,1) PRIMARY KEY,
    [MobileNumber] NVARCHAR(15) NOT NULL,
    [OTP] NVARCHAR(10) NOT NULL,
    [CreatedTime] DATETIME DEFAULT GETDATE(),
    [ExpiryTime] DATETIME NULL,
    [IsVerified] BIT DEFAULT 0,
    [AttemptCount] INT DEFAULT 0
);

-- Create Table for Aadhaar Data
CREATE TABLE [tbl_AadharData] (
    [AadharNumber] NVARCHAR(100) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(100) NULL,
    [AgeRange] NVARCHAR(100) NULL,
    [IsMobile] BIT NULL,
    [MobileLastDigit] NVARCHAR(100) NULL,
    [Gender] NVARCHAR(10) NULL,
    [Address] NVARCHAR(MAX) NULL,
    [District] NVARCHAR(100) NULL,
    [State] NVARCHAR(100) NULL,
    [Zip] NVARCHAR(100) NULL,
    [Country] NVARCHAR(100) NULL,
    [ClientId] NVARCHAR(100) NULL,
    [VerifiedBy] NVARCHAR(50) DEFAULT 'AVS_API',
    [VerifiedDate] DATETIME NULL,
    [IsVerified] BIT DEFAULT 0,
    [VerifiedByClientID] NVARCHAR(200) NULL,
    [Photo_Image] IMAGE NULL,
    [po] NVARCHAR(MAX) NULL,
    [loc] NVARCHAR(MAX) NULL,
    [vtc] NVARCHAR(MAX) NULL,
    [subdist] NVARCHAR(MAX) NULL,
    [street] NVARCHAR(MAX) NULL,
    [house] NVARCHAR(MAX) NULL,
    [landmark] NVARCHAR(MAX) NULL,
    [dist] NVARCHAR(MAX) NULL,
    [CUSTNO] NVARCHAR(50) NULL,
    [DTOPEN] DATETIME NULL,
    [CKYCStatus] NVARCHAR(50) NULL,
    [ADHAR_INCRIPT] NVARCHAR(MAX) NULL,
    [ADHARREFNO] NVARCHAR(50) NULL,
    [RBILicenseNo] NVARCHAR(50) NULL,
    [RegistrationNo] NVARCHAR(50) NULL,
    [Live_Image] IMAGE NULL,
    [Latitude] NVARCHAR(50) NULL,
    [Longitude] NVARCHAR(50) NULL,
    [LocationName] NVARCHAR(200) NULL,
    [LocationCapturedOn] DATETIME NULL
);

-- Create Table for PAN Data
CREATE TABLE [tbl_PanData] (
    [Id] INT IDENTITY(1,1),
    [PanNumber] NVARCHAR(100) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(100) NULL,
    [FatherName] NVARCHAR(100) NULL,
    [DOB] DATE NULL,
    [ClientId] NVARCHAR(100) NOT NULL,
    [VerifiedBy] NVARCHAR(100) DEFAULT 'AVS_API',
    [VerifiedDate] DATE NOT NULL
);

-- Create Table for Customer Full Details
CREATE TABLE [tbl_CustomerFullDetails] (
    [ReferenceID] INT IDENTITY(1,1) PRIMARY KEY,
    [AadharNumber] NVARCHAR(20) NULL,
    [PanNumber] NVARCHAR(20) NULL,
    [FullName] NVARCHAR(150) NOT NULL,
    [NameInMarathi] NVARCHAR(150) NULL,
    [FatherOrHusbandName] NVARCHAR(150) NOT NULL,
    [MotherName] NVARCHAR(150) NULL,
    [DOB] DATETIME NOT NULL,
    [Gender] NVARCHAR(20) NOT NULL,
    [MaritalStatus] NVARCHAR(20) NOT NULL,
    [Nationality] NVARCHAR(50) NOT NULL,
    [ResidentialStatus] NVARCHAR(50) NULL,
    [Religion] NVARCHAR(50) NULL,
    [Category] NVARCHAR(20) NULL,
    [Photo] VARBINARY(MAX) NULL,
    [Signature] VARBINARY(MAX) NULL,
    [CurrentAddress] NVARCHAR(MAX) NULL,
    [CurrentCity] NVARCHAR(100) NULL,
    [CurrentTaluka] NVARCHAR(100) NULL,
    [CurrentDistrict] NVARCHAR(100) NULL,
    [CurrentState] NVARCHAR(100) NULL,
    [CurrentPinCode] NVARCHAR(10) NULL,
    [CurrentCountry] NVARCHAR(50) DEFAULT 'India',
    [IsPermanentSame] BIT DEFAULT 0,
    [PermanentAddress] NVARCHAR(MAX) NULL,
    [PermanentCity] NVARCHAR(100) NULL,
    [PermanentTaluka] NVARCHAR(100) NULL,
    [PermanentDistrict] NVARCHAR(100) NULL,
    [PermanentState] NVARCHAR(100) NULL,
    [PermanentPinCode] NVARCHAR(10) NULL,
    [PermanentCountry] NVARCHAR(50) DEFAULT 'India',
    [OVDType_1] NVARCHAR(50) NULL,
    [OVDNumber_1] NVARCHAR(100) NULL,
    [OVDExpiryDate_1] DATETIME NULL,
    [OVDType_2] NVARCHAR(50) NULL,
    [OVDNumber_2] NVARCHAR(100) NULL,
    [OVDExpiryDate_2] DATETIME NULL,
    [OVDType_3] NVARCHAR(50) NULL,
    [OVDNumber_3] NVARCHAR(100) NULL,
    [OVDExpiryDate_3] DATETIME NULL,
    [AddressProofType] NVARCHAR(50) NULL,
    [AddressProofNumber] NVARCHAR(100) NULL,
    [FormType] NVARCHAR(10) NULL,
    [MobileNumber] NVARCHAR(15) NOT NULL,
    [AlternateMobile] NVARCHAR(15) NULL,
    [Email] NVARCHAR(100) NULL,
    [Occupation] NVARCHAR(50) NULL,
    [EmployerName] NVARCHAR(150) NULL,
    [Designation] NVARCHAR(100) NULL,
    [AnnualIncome] NVARCHAR(50) NOT NULL,
    [SourceOfFunds] NVARCHAR(50) NOT NULL,
    [IsPEP] BIT DEFAULT 0,
    [IsRelatedToPEP] BIT DEFAULT 0,
    [NomineeName] NVARCHAR(150) NULL,
    [NomineeRelationship] NVARCHAR(50) NULL,
    [NomineeDOB] DATETIME NULL,
    [NomineeAge] INT NULL,
    [NomineeSharePercent] DECIMAL(5, 2) NULL,
    [NomineeAddress] NVARCHAR(MAX) NULL,
    [GuardianName] NVARCHAR(150) NULL,
    [BranchCode] NVARCHAR(50) NULL,
    [KYCNumber] NVARCHAR(50) NULL,
    [DateOfApplication] DATETIME NULL,
    [PlaceOfApplication] NVARCHAR(100) NULL,
    [NamePrefix] NVARCHAR(20) NULL,
    [NameLast] NVARCHAR(100) NULL,
    [FatherSpouseNamePrefix] NVARCHAR(20) NULL,
    [MobileISDCode] NVARCHAR(10) NULL,
    [OVDImg1] VARBINARY(MAX) NULL,
    [OVDImg2] VARBINARY(MAX) NULL,
    [OVDImg3] VARBINARY(MAX) NULL,
    [OVDImg4] VARBINARY(MAX) NULL,
    [Form60_61_Img] VARBINARY(MAX) NULL,
    [CIFID] NVARCHAR(50) NULL,
    [BranchName] NVARCHAR(100) NULL,
    [NomineeName1] NVARCHAR(150) NULL,
    [NomineeRelationship1] NVARCHAR(50) NULL,
    [NomineeDOB1] DATETIME NULL,
    [NomineeAge1] INT NULL,
    [NomineeSharePercent1] DECIMAL(5, 2) NULL,
    [NomineeAddress1] NVARCHAR(MAX) NULL,
    [GuardianName1] NVARCHAR(150) NULL,
    [NomineeName2] NVARCHAR(150) NULL,
    [NomineeRelationship2] NVARCHAR(50) NULL,
    [NomineeDOB2] DATETIME NULL,
    [NomineeAge2] INT NULL,
    [NomineeSharePercent2] DECIMAL(5, 2) NULL,
    [NomineeAddress2] NVARCHAR(MAX) NULL,
    [GuardianName2] NVARCHAR(150) NULL,
    [NomineeName3] NVARCHAR(150) NULL,
    [NomineeRelationship3] NVARCHAR(50) NULL,
    [NomineeDOB3] DATETIME NULL,
    [NomineeAge3] INT NULL,
    [NomineeSharePercent3] DECIMAL(5, 2) NULL,
    [NomineeAddress3] NVARCHAR(MAX) NULL,
    [GuardianName3] NVARCHAR(150) NULL,
    [OVD1_CaptureDate] DATETIME NULL,
    [OVD1_Latitude] NVARCHAR(MAX) NULL,
    [OVD1_Longitude] NVARCHAR(MAX) NULL,
    [OVD1_Location] NVARCHAR(MAX) NULL,
    [OVD2_CaptureDate] DATETIME NULL,
    [OVD2_Latitude] NVARCHAR(MAX) NULL,
    [OVD2_Longitude] NVARCHAR(MAX) NULL,
    [OVD2_Location] NVARCHAR(MAX) NULL,
    [OVD3_CaptureDate] DATETIME NULL,
    [OVD3_Latitude] NVARCHAR(MAX) NULL,
    [OVD3_Longitude] NVARCHAR(MAX) NULL,
    [OVD3_Location] NVARCHAR(MAX) NULL,
    [OVD4_CaptureDate] DATETIME NULL,
    [OVD4_Latitude] NVARCHAR(MAX) NULL,
    [OVD4_Longitude] NVARCHAR(MAX) NULL,
    [OVD4_Location] NVARCHAR(MAX) NULL,
    [IsUpdated] BIT DEFAULT 0,
    [IsExcelUploaded] BIT DEFAULT 0,
    [SubmittedByUserId] INT NULL,
    [CreatedDate] DATETIME DEFAULT GETDATE()
);

-- Create Table for Admin Login
CREATE TABLE [admin] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [UserID] NVARCHAR(50) NOT NULL,
    [UserPassword] NVARCHAR(100) NOT NULL
);

-- Insert Default Admin User (Password: admin123 - Note: This should be hashed in production)
-- INSERT INTO [admin] (UserID, UserPassword) VALUES ('admin', 'admin123');

-- Create Table for App Users (Staff Members)
CREATE TABLE [tbl_AppUsers] (
    [UserID] INT IDENTITY(1,1) PRIMARY KEY,
    [Username] NVARCHAR(50) NOT NULL,
    [Password] NVARCHAR(100) NOT NULL,
    [FullName] NVARCHAR(150) NOT NULL,
    [MobileNo] NVARCHAR(15) NULL, -- Added for staff tracking
    [BranchName] NVARCHAR(100) NULL,
    [CreatedDate] DATETIME DEFAULT GETDATE()
);

-- Note: To add this column to an existing table, run:
-- ALTER TABLE [tbl_AppUsers] ADD [MobileNo] NVARCHAR(15) NULL;
